/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_D_FF_AS_1bit
#(
    parameter Default = 0
)
(
   input Set,
   input D,
   input C,
   input Clr,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q  = ~state;

    always @ (posedge C or posedge Clr or posedge Set)
    begin
        if (Set)
            state <= 1'b1;
        else if (Clr)
            state <= 'h0;
        else
            state <= D;
    end

    initial begin
        state = Default;
    end
endmodule
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module Clock_Module (
  input RST,
  input Mode, // Single-Step Mode/Full Speed Mode
  input CLK,
  input CLKA, // Automated Clock
  output SYNCLK, // Synchronized Clock
  output SYNRST // Synchronized Reset (Active LOW)

);
  wire s0;
  wire SYNCLK_temp;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  Mux_2x1 Mux_2x1_i0 (
    .sel( s0 ),
    .in_0( CLK ),
    .in_1( CLKA ),
    .out( SYNCLK_temp )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i1 (
    .Set( 1'b0 ),
    .D( 1'b1 ),
    .C( SYNCLK_temp ),
    .Clr( RST ),
    .Q( s1 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i2 (
    .Set( 1'b0 ),
    .D( s1 ),
    .C( SYNCLK_temp ),
    .Clr( RST ),
    .Q( s2 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i3 (
    .Set( 1'b0 ),
    .D( s2 ),
    .C( SYNCLK_temp ),
    .Clr( RST ),
    .Q( s3 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i4 (
    .Set( 1'b0 ),
    .D( s3 ),
    .C( SYNCLK_temp ),
    .Clr( RST ),
    .Q( SYNRST )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( s4 ),
    .C( Mode ),
    .Q( s0 )
  );
  assign s4 = ~ s0;
  assign SYNCLK = SYNCLK_temp;
endmodule
